### ISSUE TITLE
Value is undefined, expected an object

### ISSUE THREAD

**Issue by daxaxelrod** [dev-event/react-native-accordion#1]
Hi! Got an error when trying to run an example without much custom code, see attached. I also found this thread on reanimated about it.
![IMG_2001](https://user-images.githubusercontent.com/10982992/149012966-8f74f1c7-ac12-4ed2-a641-e0ab028be40e.jpg)

https://github.com/software-mansion/react-native-reanimated/issues/1758

**Comment by dev-chief** [comment]
hi

**Comment by dev-chief** [comment]
what is your reanimated version?
If new, then install the same as mine in package.json

**Comment by daxaxelrod** [comment]
Hi!

"react-native-reanimated": "2.3.0-beta.4". Will try with yours

**Comment by daxaxelrod** [comment]
That worked! Problem is that we need to stay on at least that reanimated version as prior versions cause fatal crashes for us on android.

**Comment by dev-chief** [comment]
This is because reanimated changes the API in each version. Problem persisting version
Good luck! If there are problems - feedback😊

**Comment by daxaxelrod** [comment]
Feel free to keep closed, just commented for the record.
Ive narrowed it down to 
  const style = useAnimatedStyle(() => ({
    height: size.value * progress.value + 1,
    opacity: progress.value === 0 ? 0 : 1
  }));

but have no idea why as thats a valid useAnimatedStyle

**Comment by teckbeng-payboy** [comment]
Do I need to install these 2 packages in order to work?

[react-native-reanimated](https://github.com/software-mansion/react-native-reanimated)
[react-native-redash](https://github.com/wcandillon/react-native-redash)
