### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by jared-94** [dev-event/react-native-accordion#2]
Nice lib thanks !

In my project I use `react-native-reanimated` v2.4.1 and I don't want to downgrade.

Please allow in your dependencies versions > 2.1.0:
```
"dependencies": {
    "invariant": "^2.2.4",
    "react-native-reanimated": "^2.1.0",
    "react-native-redash": "16.0.11",
    "react-native-svg": "^12.1.1"
  }
```

(the same occurs for `react-native-svg`)
To make it work, I had to remove `node_modules` subfolder (that contains these two libs)

**Comment by dev-chief** [comment]
Hi. Good👍
